### PR TITLE
Build native recommendify worker

### PR DESCRIPTION
**Pull request by tsujigiri**
The advertising said it's 10 times faster compared to the regular worker.

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
I'm ashamed to admit that I just saw this one ± a year later. 😞  Is this still relevant?

**Comment by tsujigiri** [comment]
I've forgotten about it myself. :smile: I suppose it is. We should try and see that it still works, though.

**Review by gedankenstuecke — APPROVED** [review]
I mean, looks good to me. Feel free to merge and see what happens? 😂

**Comment by tsujigiri** [comment]
Maybe later. :wink:

**Comment by gedankenstuecke** [comment]
👍  Whenever there's someone to watch over the production system? 😜

**Comment by gedankenstuecke** [comment]
this went to sleep again? :D

**Comment by tsujigiri** [comment]
It was waiting for the other pull-request, because there were changes to the sidekiq Dockerfile.

**Pull request merged**
