### PR TITLE
Fix sidekiq init script

### PR DESCRIPTION
**Pull request by tsujigiri**
Depends on opensnp/snpr#480

### CODE REVIEW

**Comment by tsujigiri** [comment]
Still not quite correct: https://travis-ci.org/openSNP/opensnp.org-docker/jobs/330473067/config

**Comment by tsujigiri** [comment]
Apparently [that's just what the config for environment variables looks like](https://docs.travis-ci.com/user/environment-variables#Defining-public-variables-in-.travis.yml). No way to know if this works but merging. 🤷

**Comment by tsujigiri** [comment]
Oh, the question is, though, what happens if we push to this repo and not to the snpr one. We won't have the commit hash, then. 😬

**Comment by tsujigiri** [comment]
This seems to work now.

**Comment by gedankenstuecke** [comment]
You let us know when it's ready for merge/review? :)

**Comment by tsujigiri** [comment]
I think it is.

**Review by gedankenstuecke — APPROVED** [review]
LGTM!

**Pull request merged**
